site_name: Dreamfect Docs
site_url: https://your-username.github.io/dreamfect-docs/
repo_url: https://github.com/your-username/dreamfect-docs
repo_name: GitHub
edit_uri: edit/main/docs/

theme:
  name: material
  logo: assets/logo.png          # Upload your logo to docs/assets/
  favicon: assets/favicon.ico    # Optional: small icon for browser tab
  features:
    - navigation.instant
    - navigation.sections
    - content.code.copy
    - toc.integrate
    - search.suggest
    - search.highlight

nav:
  - Welcome: index.md
  - Getting Started: getting-started.md
  - How Tracking Works: tracking.md
  - Meet Your Coach: coach.md
  # - Health Goals: health-goals.md
  - FAQ: faq.md
  - Terms: terms.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - codehilite
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/your-username/dreamfect-docs
    - icon: fontawesome/brands/apple
      link: https://apps.apple.com/us/app/dreamfect/id1619744155
    - icon: fontawesome/solid/globe
      link: https://dreamfect.com
